"""CSS rendering from a schema-driven zone taxonomy.

This renderer is the CSS target counterpart to the HTML renderer: it walks the
same zone taxonomy contract and projects each zone into a box-model ownership
rule, dispatching on the ``x-css`` annotation namespace. Every zone owns a named
selector (``[data-zone-id=...]``), placement comes from the parsed bounds, and
responsive collapse comes from the band/column structure. No inline styles, no
guesswork: the layout is measurable.
"""

from __future__ import annotations

from typing import Any

from generation_fabric.exceptions import SchemaError
from generation_fabric.layout.ascii_sketch import find_zone_list
from generation_fabric.schema.validation import validate_instance_against_schema, validate_schema_node

CSS_META_KEY = "x-css"


def css_meta(schema_node: Any) -> dict[str, Any]:
    """Return css-specific metadata from a schema node."""

    if not isinstance(schema_node, dict):
        return {}
    meta = schema_node.get(CSS_META_KEY, {})
    if meta is None:
        return {}
    if not isinstance(meta, dict):
        raise SchemaError(f"{CSS_META_KEY} must be an object")
    return meta


def grid_column_span(column: int, column_count: int, grid_columns: int) -> str:
    """Return the ``grid-column`` value for a zone in its band."""

    if column_count <= 1:
        return "1 / -1"
    span = max(1, grid_columns // column_count)
    start = column * span + 1
    if column == column_count - 1:
        return f"{start} / -1"
    return f"{start} / {start + span}"


def render_css_document(schema_node: dict[str, Any], data: Any) -> str:
    """Render a CSS stylesheet from a zone taxonomy contract and matching data."""

    validate_schema_node(schema_node)
    validate_instance_against_schema(schema_node, data)

    meta = css_meta(schema_node)
    container = str(meta.get("container_class", "layout"))
    grid_columns = int(meta.get("grid_columns", 12))
    breakpoint = str(meta.get("breakpoint", "720px"))
    tokens = meta.get("spacing_tokens", {})
    if not isinstance(tokens, dict):
        tokens = {}

    _item_schema, zones = find_zone_list(schema_node, data)

    gap = "var(--space-md)" if "--space-md" in tokens else "16px"
    lines: list[str] = ["/* Generated by the Generation Fabric layout CSS renderer. */"]

    if tokens:
        lines.append("")
        lines.append(":root {")
        for name, value in tokens.items():
            lines.append(f"  {name}: {value};")
        lines.append("}")

    lines.append("")
    lines.append(f".{container} {{")
    lines.append("  display: grid;")
    lines.append(f"  grid-template-columns: repeat({grid_columns}, 1fr);")
    lines.append(f"  gap: {gap};")
    lines.append("  align-items: start;")
    lines.append("}")

    for zone in zones:
        zone_id = str(zone.get("zone_id", ""))
        if not zone_id:
            continue
        role = str(zone.get("layout_role", "full_width"))
        bounds = zone.get("bounds", {}) if isinstance(zone, dict) else {}
        column = int(bounds.get("column", 0))
        column_count = int(bounds.get("column_count", 1))
        lines.append("")
        lines.append(f"/* {zone_id} — {role} */")
        lines.append(f'[data-zone-id="{zone_id}"] {{')
        lines.append(f"  grid-column: {grid_column_span(column, column_count, grid_columns)};")
        lines.append("}")

    lines.append("")
    lines.append(f"@media (max-width: {breakpoint}) {{")
    lines.append(f"  .{container} > * {{")
    lines.append("    grid-column: 1 / -1;")
    lines.append("  }")
    lines.append("}")

    return "\n".join(lines) + "\n"
