"""Component-aware CSS rendering from a web page contract.

The CSS owns three separable concerns: layout (grid placement derived from the
box model / zone bounds in the contract), component styling, and state/responsive
rules. The static component stylesheet is itself data — it lives in the
``assets/web_components.json`` contract and is projected to CSS here, so the
renderer holds no embedded stylesheet text. Markup never carries inline styles.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

from generation_fabric.css.renderer import grid_column_span
from generation_fabric.exceptions import SchemaError
from generation_fabric.layout.web_contract import zone_bounds_index

STYLESHEET_PATH = Path(__file__).resolve().parent / "assets" / "web_components.json"
GRID_COLUMNS = 12
BREAKPOINT = "720px"


@lru_cache(maxsize=1)
def _load_stylesheet() -> dict[str, Any]:
    """Load and cache the component stylesheet contract."""

    if not STYLESHEET_PATH.exists():
        raise SchemaError(f"missing CSS asset: {STYLESHEET_PATH}")
    return json.loads(STYLESHEET_PATH.read_text(encoding="utf-8"))


def _render_rule(selector: str, declarations: dict[str, str]) -> list[str]:
    """Render one CSS rule from a selector and an ordered declarations map."""

    lines = [f"{selector} {{"]
    for prop, value in declarations.items():
        lines.append(f"  {prop}: {value};")
    lines.append("}")
    return lines


def render_web_css_document(contract: dict[str, Any]) -> str:
    """Render a CSS stylesheet from a web page contract."""

    if not isinstance(contract, dict):
        raise SchemaError("web CSS rendering needs a web page contract")

    stylesheet = _load_stylesheet()
    tokens = stylesheet.get("tokens", {})
    rules = stylesheet.get("rules", [])

    bounds_index = zone_bounds_index(contract)
    components = contract.get("components", []) or []

    lines: list[str] = ["/* Generated by the Generation Fabric web CSS renderer. */", ""]
    lines.extend(_render_rule(":root", tokens))

    lines.extend(
        [
            "",
            ".gf-web-page {",
            "  display: grid;",
            f"  grid-template-columns: repeat({GRID_COLUMNS}, 1fr);",
            "  gap: var(--gf-space-md);",
            "  align-items: start;",
            "  padding: var(--gf-space-lg);",
            "}",
        ]
    )

    for component in components:
        if component.get("component_type") == "page":
            continue
        zone_id = str(component.get("zone_id", ""))
        if not zone_id:
            continue
        bounds = (bounds_index.get(zone_id) or {}).get("bounds", {})
        column = int(bounds.get("column", 0))
        column_count = int(bounds.get("column_count", 1))
        lines.append("")
        lines.append(f'/* {component.get("component_id", zone_id)} ({component.get("component_type", "")}) */')
        lines.append(f'[data-zone-id="{zone_id}"] {{')
        lines.append(f"  grid-column: {grid_column_span(column, column_count, GRID_COLUMNS)};")
        lines.append("}")

    for rule in rules:
        lines.append("")
        lines.extend(_render_rule(str(rule.get("selector", "")), rule.get("declarations", {})))

    lines.extend(
        [
            "",
            f"@media (max-width: {BREAKPOINT}) {{",
            "  .gf-web-page > * {",
            "    grid-column: 1 / -1;",
            "  }",
            "}",
        ]
    )

    return "\n".join(lines) + "\n"
